"""add_assessment_error_and_failed_status

Revision ID: 15e98be144d2
Revises: f4e6cf6103e0
Create Date: 2026-03-18 21:11:46.774167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e98be144d2'
down_revision: Union[str, None] = 'f4e6cf6103e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'error_message')
    # ### end Alembic commands ###
