"""add_brand_name_to_companies

Revision ID: 26d381978bcd
Revises: 75e3d9ba8b3c
Create Date: 2026-03-18 17:48:32.513697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d381978bcd'
down_revision: Union[str, None] = '75e3d9ba8b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('brand_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'brand_name')
    # ### end Alembic commands ###
