"""add_assessment_progress_message

Revision ID: 9f38b1b8c0d2
Revises: 15e98be144d2
Create Date: 2026-03-18 21:45:58.379795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f38b1b8c0d2'
down_revision: Union[str, None] = '15e98be144d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('progress_message', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'progress_message')
    # ### end Alembic commands ###
